### ISSUE TITLE
giphy-api-0.5.2.0 build failure with servant-0.13

### ISSUE THREAD

**Issue by DanBurton** [passy/giphy-api#17]
As seen on the Stackage build server:

```
[2 of 2] Compiling Web.Giphy        ( src/Web/Giphy.hs, dist/build/Web/Giphy.o )

src/Web/Giphy.hs:430:28: error:
    • Couldn't match expected type ‘Servant.ClientEnv’
                  with actual type ‘Maybe (GHC.Conc.Sync.TVar HTTP.CookieJar)
                                    -> Servant.ClientEnv’
    • Probable cause: ‘env’ is applied to too few arguments
      In the first argument of ‘runClientM'’, namely ‘env’
      In the first argument of ‘(.)’, namely ‘runClientM' env’
      In the second argument of ‘(.)’, namely
        ‘runClientM' env . Reader.runReaderT giphy’
    |
430 |       liftIO . runClientM' env . Reader.runReaderT giphy $ GiphyContext conf
    |                            ^^^
```

I was able to reproduce this failure locally like so:

```bash
stack unpack giphy-api-0.5.2.0 && cd giphy-api-0.5.2.0
edit stack.yaml # add the following stack.yaml
stack build 
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- servant-0.13
- http-types-0.12.1
- servant-client-0.13
- servant-client-core-0.13
```

**Comment by DanBurton** [comment]
I've removed giphy-api from the Stackage nightly build plan, and unfortunately it won't appear in the initial LTS 11 release.

To get back into nightly, open a PR on the Stackage repo as usual. To get into LTS 11, open an issue on https://github.com/fpco/lts-haskell/issues.

**Comment by passy** [comment]
@DanBurton Thanks for the heads-up! I'll look into upgrading it to work with servant 0.13 as soon as I find some time. I appreciate the detailed repro steps. :)

**Comment by passy** [comment]
Upgraded. :)
